### ISSUE TITLE
About pretrain tokenizer

### ISSUE THREAD

**Issue by NateBYWang** [jiangsongtao/TinyMed#10]
Hi, thanks for this impressive work.
I'm trying to run scripts/train_scripts/stablelm/pretrain.sh.
However I found the tokenizer I loaded from stablelm2-1_6b is different from the arch in code. This leaded to errors shown below.
![image](https://github.com/user-attachments/assets/afa493e4-b25e-43d4-b860-c30074d5fe66)
It's supposed to be this or maybe something wrong with weights and corresponding code?
Thanks for your timely reply.

**Comment by NateBYWang** [comment]
![image](https://github.com/user-attachments/assets/84b2b25d-5766-4560-9676-535736aff249)
Also,I download stablelm 2 1.6b from official hf. I have warnings like above. Maybe I use the wrong model or weights? Any comment? THX

**Comment by jiangsongtao** [comment]
Sorry for the late reply. For question 1, you need to change the default tokenizer of StableLM to AutoTokenizer. For question 2, the warning is normal and will not affect the results.
