### ISSUE TITLE
About the training loss

### ISSUE THREAD

**Issue by AlexandreWANG915** [jiangsongtao/TinyMed#11]
Hi, thank you for your nice work! I am trying to train the model in three stages. Can you give an approximate final loss for each stage, as my GPU is different from yours and uses different parameters?

**Comment by jiangsongtao** [comment]
Hello! Sorry for the late response. Each stage's weight file (trainer_state.json) contains this information.

**Comment by REAL-Lab-NU** [comment]
Thanks!

**Comment by AlexandreWANG915** [comment]
Thanks!
