### ISSUE TITLE
The test.json for VQA_RAD

### ISSUE THREAD

**Issue by Eldo-rado** [jiangsongtao/TinyMed#2]
Hi @jiangsongtao 

Great work, appreciate your contributions. 
Could you provide the test.json for VQA_RAD? 

Thanks in advance.

**Comment by jiangsongtao** [comment]
Thank you for your attention to our work! I have updated the test.json for the three VQA datasets. If you have any questions, please feel free to contact me.

**Comment by jiangsongtao** [comment]
https://drive.google.com/file/d/1pyGsm8G0Gig63DAnOdLuUn3IyxrztWtR/view?usp=sharing

**Comment by Eldo-rado** [comment]
Thank you for your prompt reply! I'd like to confirm if these files were generated using scripts based on the original dataset?

In addition, compared to llava-med, in [run_eval.py,](https://github.com/jiangsongtao/TinyMed/blob/9a059009588b9f9377beb7559730c468963702e6/run_eval.py#L39) do we not need candidate.json for calculating open accuracy? Which metrics in the table correspond to the open and closed accuracies in the code?

thx!

**Comment by jiangsongtao** [comment]
Yes. These test.json files are all generated from the original files. Unfortunately, the original candidate.json used in LLaVA-Med was not provided by the authors, so we excluded it when calculating metrics. We rewrote the code to ensure consistency with the paper's methodology. For questions under the OPEN setting, we use recall as the primary reference metric, while for questions under the CLOSED setting, we use accuracy as the primary reference metric.

**Comment by Eldo-rado** [comment]
got it, thanks a lot!

**Comment by jiangsongtao** [comment]
No problem.

**Comment by Eldo-rado** [comment]
Hi@jiangsongtao !

Sorry to bother you again. The VQA-RAD I downloaded from the official website contains a total of 2247 IDs. And your train and test sets contain 3064 and 451 IDs respectively, by extracting the question, question rephrase, and question frame from each sample and separately constructing a new question-answer pair. However, this may result in identical question-answer pairs, as shown in the figure below.
![b58c86b74581daf151434d3c9328b559](https://github.com/jiangsongtao/TinyMed/assets/128444206/afadbcc3-6c78-44d8-a173-e9a1737fd6e5)![b58c86b74581daf151434d3c9328b559](https://github.com/jiangsongtao/TinyMed/assets/128444206/b1e4e305-f696-439b-8e1c-f1251ad3264a)

Is this the default processing method for the VQA-RAD dataset? I'm new to Medical VQA and not familiar with this area, so I appreciate your help. Thank you!

**Comment by Eldo-rado** [comment]
thx~

**Comment by jiangsongtao** [comment]
No problem~
