### ISSUE TITLE
Error when Loading Model: SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by Aya0813** [jiangsongtao/TinyMed#3]
Hello,

I've been trying to do the Web serving of the [TinyMed](https://github.com/jiangsongtao/TinyMed) model from this repository, but I've encountered a persistent issue when attempting to load the model using the provided scripts. Below, I've outlined the error message and the context around it:

**Issue Description:**
When running the script model_vqa.py, I encounter the following traceback:

```
**Traceback (most recent call last):
  File "/scratch/ae2195/TinyMed/moellava/eval/model_vqa.py", line 145, in <module>
    eval_model(args)
  File "/scratch/ae2195/TinyMed/moellava/eval/model_vqa.py", line 36, in eval_model
    tokenizer, model, processor, context_len = load_pretrained_model(model_path, args.model_base, model_name)
  File "/scratch/ae2195/TinyMed/moellava/model/builder.py", line 479, in load_pretrained_model
    model = AutoModelForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, **kwargs)
  File "/home/ae2195/miniconda3/envs/tinymed/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/home/ae2195/miniconda3/envs/tinymed/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3852, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/ae2195/miniconda3/envs/tinymed/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4261, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/home/ae2195/miniconda3/envs/tinymed/lib/python3.10/site-packages/transformers/modeling_utils.py", line 509, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge**

```
**Modifications Made:**
I made a single change in the repository's code to address an initial issue where a certain path was not recognized (/home/songtaojiang/MobileVLM/clip-vit-large-patch14-336). Specifically, I modified a line in the file TinyMed/moellava/model/multimodal_encoder/builder.py from:

**image_tower = getattr(image_tower_cfg, 'mm_image_tower', getattr(image_tower_cfg, 'image_tower', None))**
to:
**image_tower = "openai/clip-vit-large-patch14-336**

Could you please help me understand what might be causing the SafetensorError and how I might resolve it? Additionally, if the modification I made could be contributing to this issue, any guidance on a better approach would be greatly appreciated.

Thank you for your time and assistance!

**Comment by jiangsongtao** [comment]
Hello, It seems that the issue might not be with the image encoder path. What is the path of your model? Does it include the 'moe' name? Normally, during inference, the model should use the 'model = EvalMoExxxx.from_pretrained' method. You could also try updating the transformer to the latest version. Additionally, I recommend using the model_vqa_med.py file for testing.

**Comment by Aya0813** [comment]
Thank you for getting back to me! 

Whether it is the model_vqa.py or model_vqa_med.py, I always get the following error after the checkpoints have been loaded: 

```
Traceback (most recent call last):
  File "/scratch/ae2195/TinyMed/moellava/eval/model_vqa.py", line 150, in <module>
    eval_model(args)
  File "/scratch/ae2195/TinyMed/moellava/eval/model_vqa.py", line 77, in eval_model
    image_tensor = image_processor.preprocess(image, return_tensors='pt')['pixel_values'][0]
AttributeError: 'NoneType' object has no attribute 'preprocess'
```
Any suggestions on what could solve this error? 

Thank you!

**Comment by Aya0813** [comment]
Hi,

Thank you for your previous suggestions. I tried using the model_vqa_med.py script for testing and ensured that the mm_image_tower path in the config file is correct. However, I am still encountering an issue where the image processor is not being loaded correctly.

Here are the specific details of the error:

Processor details:
image: <class 'NoneType'>
video: <class 'NoneType'>

``
Traceback (most recent call last):
  File "/scratch/ae2195/TinyMed/moellava/eval/model_vqa.py", line 359, in <module>
    eval_model(args)
  File "/scratch/ae2195/TinyMed/moellava/eval/model_vqa.py", line 248, in eval_model
    raise ValueError("Image processor is missing from the loaded processor.")
ValueError: Image processor is missing from the loaded processor.
``

Despite specifying the correct path to the vision tower in the configuration, the processor is still not being loaded properly. Below is the relevant part of the config:

``
{
  "mm_image_tower": "/scratch/ae2195/TinyMed/cache_dir/models--openai--clip-vit-large-patch14-336"
}
``

I would appreciate any further guidance or suggestions on what might be causing this issue and how to resolve it.

Thank you!

**Comment by jiangsongtao** [comment]
Hi, are you using the updated builder.py file? You can try to add a print statement within the if statement to check if the function build_image_tower correctly runs.

**Comment by jiangsongtao** [comment]
Or you can simply try this:
def build_image_tower(image_tower_cfg, **kwargs):
    return CLIPVisionTower("your clip based vit path", args=image_tower_cfg, cache_dir='./cache_dir', **kwargs)

**Comment by Aya0813** [comment]
Hi, 
Thank you for your suggestion. 
I implemented your suggestion, however, now I am getting an error of a file missing in the hugging face model. Here is the full error. 

```
Traceback (most recent call last):
  File "/scratch/ae2195/TinyMed/moellava/eval/model_vqa.py", line 206, in <module>
    eval_model(args)
  File "/scratch/ae2195/TinyMed/moellava/eval/model_vqa.py", line 49, in eval_model
    tokenizer, model, processor, context_len = load_pretrained_model(model_path, model_base, model_name)
  File "/scratch/ae2195/TinyMed/moellava/model/builder.py", line 472, in load_pretrained_model
    model = PeftModel.from_pretrained(model, model_path)
  File "/home/ae2195/miniconda3/envs/tinymed/lib/python3.10/site-packages/peft/peft_model.py", line 244, in from_pretrained
    PeftConfig._get_peft_type(
  File "/home/ae2195/miniconda3/envs/tinymed/lib/python3.10/site-packages/peft/utils/config.py", line 183, in _get_peft_type
    raise ValueError(f"Can't find '{CONFIG_NAME}' at '{model_id}'")
ValueError: Can't find 'adapter_config.json' at '/scratch/ae2195/TinyMed/TinyMed/Tinymed-stablelm-1.6b'

```

I got the both the [Tinymed-stablelm-1.6b](https://huggingface.co/JsST/TinyMed/tree/main/Tinymed-stablelm-1.6b)
 and [Tinymed-phi2] (https://huggingface.co/JsST/TinyMed/tree/main/Tinymed-phi2) models from your hugging face, however, the file adapter_config.json is missing in both.
--

Any insights regarding this would be helpful. 
Thank you!

**Comment by jiangsongtao** [comment]
Hello! It's strange that you're running model = PeftModel.from_pretrained(model, model_path) during loading. Typically, if you're using the moe-stablelm version, you would expect to execute model = EvalMoELLaVAStablelmForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, **kwargs) instead, since our provided weights don't incorporate lora.I've uploaded a new builder.py file. 
You can try it again, and please pay attention to whether the model loading process correctly executes the branch for EvalMoELLaVAStablelmForCausalLM.

**Comment by jiangsongtao** [comment]
Hello! I hope you're well. During this period, I've uploaded new model weights and fixed some bugs. If you encounter any issues, feel free to reach out to me. Since it's been a while without a response, I'm closing this issue for now.
