### ISSUE TITLE
Cannot import HeirarchicalMoE

### ISSUE THREAD

**Issue by hwei-hw** [jiangsongtao/TinyMed#4]
In the file: `moellava/model/builder.py`, the code to import `HeirarchicalMoE` encounter the `NotFound` errors:

`from moellava.model.language_model.mixture_of_experts import HeirarchicalMoE`

And still cannot find this module by searching the keyword `HeirarchicalMoE` in the whole project. So, is the whole project complete?

Also, the `eval_metrics` module in `run_eval.py` cannot be found.

**Comment by jiangsongtao** [comment]
Hello, we have already uploaded the eval_metrics.py file. Hierarchical MoE and more MoE architectures may be incorporated into our approach in future updates. Currently, we are still using the MoE structure from DeepSpeed.

**Comment by hwei-hw** [comment]
Thanks for your timely and kind reply. But sorry that I still cannot find the `eval_metrics.py` in the project. Have you uploaded it? Or, will upload it later?

Thanks a lot!

**Comment by jiangsongtao** [comment]
Sorry for that, I have already uploaded the required file to this location: https://github.com/jiangsongtao/TinyMed/tree/main/moellava/eval/eval_metrics. Feel free to contact me if you have any other questions.
