### ISSUE TITLE
Could not locate the configuration_phi.py

### ISSUE THREAD

**Issue by hwei-hw** [jiangsongtao/TinyMed#5]
I try to run the `evaluation` step to follow the code in the `readme`. 
First, I download the checkpoints from the huggingface. And then set `--model-path /data2/TinyMed/pretrained_weights/Tinymed-phi2` to run the code. 
But encounter the following errors:
`Could not locate the configuration_phi.py inside /data2/TinyMed/pretrained_weights/Tinymed-phi2`

So, Is there a missing file? Or caused by other reasons. I run this code on two A100 (80GB).

**Comment by hwei-hw** [comment]
By the way, I also try to use `Tinymed-stablelm-1.6b` but still get the errors:

> Traceback (most recent call last):
  File "/home/haowei/project/TinyMed/model_vqa_med.py", line 246, in <module>
    eval_model(args)
  File "/home/haowei/project/TinyMed/model_vqa_med.py", line 107, in eval_model
    tokenizer, model, image_processor, context_len = load_pretrained_model(model_path, args.model_base, model_name)
  File "/home/haowei/project/TinyMed/moellava/model/builder.py", line 505, in load_pretrained_model
    model = AutoModelForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, trust_remote_code=True, **kwargs)
  File "/home/haowei/anaconda3/envs/llavaMed/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/haowei/anaconda3/envs/llavaMed/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 926, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/home/haowei/anaconda3/envs/llavaMed/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 632, in __getitem__
    raise KeyError(key)
KeyError: 'moe_llava_stablelm'

Could you help me with these errors? Thanks a lot

**Comment by jiangsongtao** [comment]
Hello, please ensure that 'moe' is included in the file path name, such as 'moe_tinymed_stablelm'.

**Comment by hwei-hw** [comment]
Thanks, I will try it. 

For the first issue, do you have any suggestions?

**Comment by jiangsongtao** [comment]
Hello, there is a 'configuration_phi' file in the project. It seems like you should modify the path for 'AutoConfig' in 'config.json' to correspond to your specific path.

**Comment by hwei-hw** [comment]
The `config.json` in the provided checkpoints? The following shows the subset of this `config.json` :

> {
  "_name_or_path": "/home/songtaojiang/TinyLLaVABench/MoE-LLaVA/checkpoints/llavaphi-2.7b-finetune-3epoch",
  "architectures": [
    "MoELLaVAPhiForCausalLM"
  ],
  "attention_dropout": 0.0,
  "auto_map": {
    "AutoConfig": "configuration_phi.PhiConfig",
    "AutoModelForCausalLM": "modeling_phi.PhiForCausalLM"
  },

So, I need to modify ` "AutoConfig": "configuration_phi.PhiConfig"`? If yes, how should I set this? Thanks

**Comment by jiangsongtao** [comment]
Just replace configuration_phi.PhiConfig to xxxx.configuration_phi.PhiConfig, which depends on your path.

**Comment by hwei-hw** [comment]
I modify this line as:
> {
  "_name_or_path": "/home/songtaojiang/TinyLLaVABench/MoE-LLaVA/checkpoints/llavaphi-2.7b-finetune-3epoch",
  "architectures": [
    "MoELLaVAPhiForCausalLM"
  ],
  "attention_dropout": 0.0,
  "auto_map": {
    "AutoConfig": "/home/haowei/project/TinyMed/moellava/model/language_model/phi/configuration_phi.py",
    "AutoModelForCausalLM": "modeling_phi.PhiForCausalLM"
  },

But still the errors:

> shutil.SameFileError: '/home/haowei/project/TinyMed/moellava/model/language_model/phi/configuration_phi.py' and PosixPath('/home/haowei/project/TinyMed/moellava/model/language_model/phi/configuration_phi.py') are the same file

**Comment by hwei-hw** [comment]
And I also found this checkpoint `/home/songtaojiang/TinyLLaVABench/MoE-LLaVA/checkpoints/llavaphi-2.7b-finetune-3epoch` is required to run. Could your provide the link to download this one? Thanks

**Comment by jiangsongtao** [comment]
Hello, I have already uploaded it to https://huggingface.co/JsST/TinyMed. You can also try using phi.configuration_phi.PhiConfig in AutoConfig.

**Comment by hwei-hw** [comment]
Still errors:

> Traceback (most recent call last):
  File "/home/haowei/project/TinyMed/model_vqa_med.py", line 246, in <module>
    eval_model(args)
  File "/home/haowei/project/TinyMed/model_vqa_med.py", line 107, in eval_model
    tokenizer, model, image_processor, context_len = load_pretrained_model(model_path, args.model_base, model_name)
  File "/home/haowei/project/TinyMed/moellava/model/builder.py", line 505, in load_pretrained_model
    model = AutoModelForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, trust_remote_code=True, **kwargs)
  File "/home/haowei/anaconda3/envs/tinymed/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 526, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/haowei/anaconda3/envs/tinymed/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1109, in from_pretrained
    config_class = get_class_from_dynamic_module(
  File "/home/haowei/anaconda3/envs/tinymed/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 483, in get_class_from_dynamic_module
    module_file, class_name = class_reference.split(".")
ValueError: too many values to unpack (expected 2)

Where I set:

>   "auto_map": {
    "AutoConfig": "phi.configuration_phi.PhiConfig",
    "AutoModelForCausalLM": "modeling_phi.PhiForCausalLM"
  },

**Comment by jiangsongtao** [comment]
Normally, EvalMoELLaVAStablelmForCausalLM should be executed when the path contains 'moe', 'llava', and 'stablelm'. I checked the path where you encountered the error and noticed that you might be missing these. I re-cloned this project, and this code runs fine on my computer. You could also do some simple debugging to see where it's running up to in builder.py.

**Comment by hwei-hw** [comment]
Thanks for your kind reply and sorry for my previous comment. And I will do more debugging work following your suggestions. Thanks again.

**Comment by jiangsongtao** [comment]
Never mind. Thank you for your interest in our work. TinyMed will be updated within two weeks with a new version, and I will also provide a more detailed readme.md at that time. Feel free to contact me if you have any further questions.

**Comment by hwei-hw** [comment]
Thanks a lot! And now, I basically reproduce your results in the paper by inference on your provided checkpoints.

TinyMoE-Med (Phi2-2.7B×4:3.6B): 84.56(paper) vs 83.46 (mine)
TinyMoE-Med (StableLM-1.6B×4:2.0B): 83.82(paper) vs 82.72 (mine)

The point is the checkpoints in the huggingface. You rename the previous `Tinymed-ph2` directory to `MoE-Tinymed-ph2-llava` but delete these files: `model-00001-of-00003.safetensors, model-00002-of-00003.safetensors, model-00003-of-00003.safetensors, pytorch_model.bin and training_args.bin` (the version: 141affd9a1f2ea9847c0392887957f2760b77f52). By the way, I don't know why you delete these files. 

SO, I move these missing files from the previous `Tinymed-ph2` directory to new `MoE-Tinymed-ph2-llava` directory. And then, modify the `_name_or_path` and `mm_image_tower` term in the `config.json` in `MoE-Tinymed-ph2-llava`  directory as the path in your machine. For example:

> "_name_or_path": "/data2/TinyMed/pretrained_weights/llavaphi-2.7b-finetune-3epoch", # this is the download path in my machine
"mm_image_tower": "/data2/TinyMed/pretrained_weights/clip-vit-large-patch14-336",

And finally, for the evaluation step, set `--conv-mode` as `phi` instead of the default `simple` would work. 

The same steps for the `MoE-Tinymed-stablelm-llava`.

**Comment by jiangsongtao** [comment]
Hello, thank you for your detailed steps. Previously, some files and corresponding model weights were not synchronized when I used a VPN to upload to Hugging Face, resulting in some files being missed. I have now re-uploaded the model weights and updated the simple conv_mode in the conversations.py file. I apologize for any confusion this may have caused.

**Comment by hwei-hw** [comment]
Thanks a lot.

And reminder to update the link for these weights in the `Readme.md`.
