### ISSUE TITLE
About Pretrained and SFT Image.

### ISSUE THREAD

**Issue by NyKxo1** [jiangsongtao/TinyMed#9]
Can you share your Pretrained and SFT Image, downloading via download_image.py is really slow. I would appreciate if you would share it!

**Comment by jiangsongtao** [comment]
Sorry for the delayed response. I’ve optimized the download code to use multithreading. Given the large amount of image data, I plan to upload all the images once I have consulted with the original dataset author.
Thank you for your patience!
